ignore:
  - "bot/libs/ui/**" # These are Discord UI stuff, so it's untestable (even w/ dpytest)
  - "bot/libs/utils/formats.py" # Used by RDanny so we know it works.
  - "bot/libs/utils/help.py" # How can you test this...
  - "bot/libs/utils/logger.py" # Untestable. Doesn't return anything
  - "bot/libs/utils/time.py" # used by rdanny in prod so it is guarneeted to work
  - "bot/libs/utils/pages/**" # you can't test the pages module srry
  - "bot/cogs/**" # can't really test cogs
  - "aimikobot.py"
  - "aimikocore.py"
  - "bot/libs/utils/checks.py" # pretty sure that there is no way to literally test
  - "bot/libs/utils/prefix.py" # can't test due to tied with the on_guild_join events and requires a working bot. cannot be mocked
